name: Build
on:
  push:
    branches:
      - master
      - branch/*
  pull_request:
     types: [opened, synchronize]
jobs:
  build:
    strategy:
      matrix:
        target:
          - arm-linux-gnueabihf
          - aarch64-linux-gnu
        host:
          - ubuntu-22.04
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - run: sudo apt install -y gcc-${{ matrix.target}} build-essential
    - run: ./autogen.sh
    - run: ./configure --host=${{ matrix.target }} --prefix=/usr
    - run: make binary-dist

    - uses: actions/upload-artifact@v4
      with:
        name: bootcount-${{ matrix.target }}.tar.gz
        path: dist/*.tar.gz
